CREATE TABLE STORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  email_id VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  story VARCHAR(250) DEFAULT NULL
);

CREATE TABLE GANG (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  email_id VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  gangtype VARCHAR(250) NULL,
  age VARCHAR(250) NULL,
  meetdate VARCHAR(250) NULL,
  description VARCHAR(250) NULL
);